config/routes.rb
Rails.application.routes.draw do
  resources :slames
  resources :sistemaslas
  resources :gruposlas
  resources :bonificacoes
  resources :detalhamentos do
    get 'toogle_status',  on: :member
  end
  resources :metas do
    get 'detalhar',       on: :member
    get 'fechar_mes',     on: :collection
  end
  resources :configs
  resources :ganhos
  resources :dificuldades
  resources :tipos
  devise_for :usuarios, path_prefix: :auth
  resources :usuarios
  root to: 'welcome#index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meta.rb
class Meta < ApplicationRecord

  validates :nome, presence: true

  belongs_to :tipo, optional: true
  belongs_to :dificuldade, optional: true
  belongs_to :ganho, optional: true
  belongs_to :usuario, optional: true

  scope :periodo , -> (data_referencia) { where("to_char(datameta, 'MM') = ? and to_char(datameta, 'YYYY') = ?", data_referencia.to_date.strftime('%m'), data_referencia.to_date.strftime('%Y')) }
  scope :com_responsavel, -> (usuario) { where(usuario_id: usuario) }
  scope :n1_todo, -> (datareferencia, nivel) { where(nivel: nivel, datameta: datareferencia.beginning_of_month..datareferencia.end_of_month) }
  scope :n1_done, -> (datareferencia, nivel) { where(nivel: nivel, status: true, datameta: datareferencia.beginning_of_month..datareferencia.end_of_month) }
  scope :metas_done_mes, -> (datareferencia) { where(status: true, datameta: datareferencia.beginning_of_month..datareferencia.end_of_month) }
  scope :metas_not_done, -> (datareferencia) { where("to_char(datameta, 'MM') = ? AND to_char(datameta, 'YYYY') = ? AND status = ?", datareferencia.to_date.strftime('%m'), datareferencia.to_date.strftime('%Y'), false) }
  scope :meta_done, -> (datareferencia) { where("to_char(datameta, 'MM') = ? AND to_char(datameta, 'YYYY') = ? AND status = ?", datareferencia.to_date.strftime('%m'), datareferencia.to_date.strftime('%Y'), true) }

  has_many :detalhamentos, dependent: :destroy
  accepts_nested_attributes_for :detalhamentos, :allow_destroy => true

  def self.metas_done(data)
    @metas_mes = self.periodo(data)
    @metas_mes.each do |meta|
      if self.andamento(meta.id) == 100.0
        meta.update :status => true
      else
        meta.update :status => false
      end
    end
    self.metas_done_mes(data).count
  end

  def self.andamento(id)
    conta_detalhamento = Detalhamento.where(meta_id: id).count
    conta_concluida = Detalhamento.where(meta_id: id, status: true).count
    porcento_concluida = conta_concluida.to_f / conta_detalhamento.to_f * 100
  end

  def self.fechar_mes(data)
    datareferencia = data.to_date
    @metas = Meta.where(datameta: datareferencia.beginning_of_month..datareferencia.end_of_month)
    @metas.each do |meta| # altera o status da meta de acordo com as metas finalizadas ou não.
      puts "==> Valor da meta entrege #{self.andamento(meta.id)}"
      if self.andamento(meta.id) == 100.0
        meta.update :status => true
      else
        meta.update :status => false
      end
    end
    conta_metas_n1 = Meta.n1_todo(datareferencia, 1).count
    conta_metas_n2 = Meta.n1_todo(datareferencia, 2).count
    conta_metas_n3 = Meta.n1_todo(datareferencia, 3).count

    conta_metas_n1_done = Meta.n1_done(datareferencia, 1).count
    conta_metas_n2_done = Meta.n1_done(datareferencia, 2).count
    conta_metas_n3_done = Meta.n1_done(datareferencia, 3).count
    @total_metas_done = conta_metas_n3_done + conta_metas_n2_done + conta_metas_n1_done

    @pontuacao_n3 = conta_metas_n3_done.to_f * 6 / conta_metas_n3.to_f
    @pontuacao_n2 = conta_metas_n2_done.to_f * 3 / conta_metas_n2.to_f
    @pontuacao_n1 = conta_metas_n1_done.to_f * 1 / conta_metas_n1.to_f
    @total_bnf = @pontuacao_n3.round(2) + @pontuacao_n2.round(2) + @pontuacao_n1.round(2)

    @pontosn3 = conta_metas_n3 * 6
    @pontosn2 = conta_metas_n2 * 3
    @pontosn1 = conta_metas_n1 * 1
    @total_pontos = @pontosn3 + @pontosn2 + @pontosn1
    @pontos_done_n3 = conta_metas_n3_done * 6
    @pontos_done_n2 = conta_metas_n2_done * 3
    @pontos_done_n1 = conta_metas_n1_done * 1
    @total_pontos_done = @pontos_done_n3 + @pontos_done_n2 + @pontos_done_n1

    Bonificacao.create  quantidaden3: conta_metas_n3, quantidaden2: conta_metas_n2, quantidaden1: conta_metas_n1,
    alcancadon3: conta_metas_n3_done, alcancadon2: conta_metas_n2_done,
    alcancadon1: conta_metas_n1_done, totalalcancado: @total_metas_done,
    bnfalcancadan3: @pontuacao_n3, bnfalcancadan2: @pontuacao_n2,
    bnfalcancadan1: @pontuacao_n1, totalbnf: @total_bnf, pontuacaon3: @pontosn3,
    pontuacaon2: @pontosn2, pontuacaon1: @pontosn1, totalpontuacao: @total_pontos,
    pontuacaodonen3: @pontos_done_n3, pontuacaodonen2: @pontos_done_n2,
    pontuacaodonen1: @pontos_done_n1, totalpontuacaodone: @total_pontos_done,
    periodo: datareferencia

  end

  before_save :atribui_nivel
  def atribui_nivel
    ganho_matriz = Config.all
    ganho_matriz.each do |matriz|
      @val_ganho = matriz.valor_ganho
      @val_dificuldade = matriz.valor_dificuldade
      @val_tipo = matriz.valor_tipo
    end
    ganho = Ganho.find(self.ganho_id).valor_ganho
    tipo = Tipo.find(self.tipo_id).valor_tipo
    dificuldade = Dificuldade.find(self.dificuldade_id).valor_dificuldade
    self.coeficienteganho = ganho * @val_ganho
    self.coeficientetipo = tipo * @val_tipo
    self.coeficientedificuldade = dificuldade * @val_dificuldade
    self.pontuacao =  self.coeficienteganho + self.coeficientetipo + self.coeficientedificuldade
    if self.pontuacao <= 55
      self.nivel = 1
    elsif self.pontuacao > 55 && self.pontuacao <= 80
      self.nivel = 2
    elsif self.pontuacao > 80
      self.nivel = 3
    end
  end

end

app/controllers/metas_controller.rb
class MetasController < ApplicationController
  before_action :set_meta, only: [:show, :edit, :detalhar, :update, :destroy]

  respond_to :html
  has_scope :periodo
  has_scope :com_responsavel
  has_scope :metas_not_done
  has_scope :meta_done

  BOM = "\377\376" #Byte Order Mark
  # require 'iconv'

  def index
    if params[:periodo]
      @mes_referencia = params[:periodo].to_date
    else
      @mes_referencia = Date.today
    end
    # FIXME Acrescentado para evitar bugs nos dias > 28
    #       Deve ser corrigido pois pode afetar o fluxo de caixa do mês
    @mes_referencia = @mes_referencia.change(day: 1)
    data_corrente = Date.today
    params[:periodo] = l(data_corrente) unless params[:periodo]
    @metas = apply_scopes(Meta).all.order('pontuacao DESC')
    respond_to do |format|
      format.html
      format.csv { export_csv(@metas) }
    end
    # respond_with(@metas)
  end

  def show
    respond_with(@meta)
  end

  def detalhar

  end

  def new
    @meta = Meta.new
    respond_with(@meta)
  end

  def edit
  end

  def fechar_mes
    referencia = params[:data_referencia].to_date
    Meta.fechar_mes(referencia)
    respond_to do |format|
      format.html { redirect_to metas_url, notice: 'Mes fechado' }
    end
  end

  def create
    @meta = Meta.new(meta_params)
    @meta.save
    respond_with(@meta)
  end

  def update
    @meta.update(meta_params)
    respond_with(@meta)
  end

  def destroy
    @meta.destroy
    respond_with(@meta)
  end

  private
  def set_meta
    @meta = Meta.find(params[:id])
  end

  def meta_params
    params.require(:meta).permit(:nome, :tipo_id, :dificuldade_id, :ganho_id, :usuario_id, :datameta,
    detalhamentos_attributes: [:id, :item, :meta_id, :_destroy])
  end

  def export_csv(projects)
    filename = I18n.l(Time.now, :format => :short) + "- Projects.csv"
    content = Meta.to_csv(projects)
    content = BOM + Iconv.conv("utf-16le", "utf-8", content)
    send_data content, :filename => filename
  end
end

app/helpers/metas_helper.rb
module MetasHelper
  
  def andamento(id)
    conta_detalhamento = Detalhamento.where(meta_id: id).count
    conta_concluida = Detalhamento.where(meta_id: id, status: true).count
    porcento_concluida = conta_concluida.to_f / conta_detalhamento.to_f * 100
  end
  
  def background_meta(meta)
    if meta == 3
      "background-color:  #6aa84f; color: #000;"
    elsif meta == 2
      "background-color:  #93c47d; color: #000;"
    else
      "background-color:  #d9ead3; color: #000;"
    end
  end
  
  def concluido(porcento)
    if porcento.present?
      if porcento == 100
        "success"
      elsif porcento < 100 && porcento > 0
        "warning"
      elsif porcento == 0
        "danger"
      end
    else
      "danger"
    end
  end
  
  
end

app/views/metas/_form.html.erb
<%= simple_nested_form_for(meta, multipart: true) do |f| %>
<div class="panel panel-default">
  <div class="panel-body">
    <% if meta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meta.errors.count, "erro") %></h2>

      <ul>
        <% meta.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="row">
      <%= f.input :nome, wrapper_html: {class: 'col-md-12'} %>
    </div>
    <div class="row">
      <%= f.association :tipo, collection: Tipo.all.order('valor_tipo DESC') , label_method: :nome, wrapper_html: {class: 'col-md-3'} %>
      <%= f.association :dificuldade, collection: Dificuldade.all.order('valor_dificuldade DESC'), label_method: :nome, wrapper_html: {class: 'col-md-3'} %>
      <%= f.association :ganho, collection: Ganho.all.order('valor_ganho DESC'), label_method: :nome, wrapper_html: {class: 'col-md-3'} %>
      <%= f.association :usuario, collection: Usuario.all.order('nome'), label_method: :nome, wrapper_html: {class: 'col-md-3'} %>
      <%= f.input :datameta, label: "Periodo da meta", wrapper_html: {class: 'col-md-4'} %>
    </div>

  </div>

  <div class="panel-footer">
    <%= f.submit "Salvar", class: 'btn btn-primary' %> ou
    <%= link_to "Cancelar", :back, class: 'btn btn-default' %>
    <%= link_to "Apagar", @meta,
    method: :delete,
    class: 'btn btn-danger pull-right',
      data: { confirm: 'Tem certeza que quer apagar?' } if @meta.persisted? %>
    </div>
  </div>
  <% end %>

app/views/metas/_formdetalhar.html.erb
<%= simple_nested_form_for(meta) do |f| %>
<div class="panel panel-default">
  <div class="panel-body">
    <% if meta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meta.errors.count, "erro") %></h2>

      <ul>
        <% meta.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="row">
      <%= f.input :nome, wrapper_html: {class: 'col-md-12'}, input_html: { :disabled => true} %>
    </div>
    <div class="row">
      <%= f.association :tipo, collection: Tipo.all.order('nome') , label_method: :nome, wrapper_html: {class: 'col-md-3'}, input_html: { :disabled => true} %>
      <%= f.association :dificuldade, collection: Dificuldade.all.order('nome'), label_method: :nome, wrapper_html: {class: 'col-md-3'}, input_html: { :disabled => true} %>
      <%= f.association :ganho, collection: Ganho.all.order('nome'), label_method: :nome, wrapper_html: {class: 'col-md-3'}, input_html: { :disabled => true} %>
      <%= f.association :usuario, collection: Usuario.all.order('nome'), label_method: :nome, wrapper_html: {class: 'col-md-3'}, input_html: { :disabled => true} %>
    </div>

    <%= f.fields_for :detalhamentos do |i| %>
    <div class="row">
      <div class="col-sm-12">
        <%= i.hidden_field :meta_id %>

        <%= i.input :item, wrapper_html: {class: 'col-md-8'}%>
        <br>        
        <%= i.link_to_remove class: "btn btn-danger" do %>
        <i class="zmdi zmdi-delete"></i> Remove
        <% end %>
      </div>
    </div>
    <% end %>
    <div class="row">
      <div class="col-sm-12">
        <%= f.link_to_add "Adicionar item", :detalhamentos, class: "btn btn-primary" %>
      </div>
    </div>

  </div>

  <div class="panel-footer">
    <%= f.submit "Salvar", class: 'btn btn-primary' %> ou
    <%= link_to "Cancelar", :back, class: 'btn btn-default' %>
    <%#= link_to "Apagar", @meta,
    method: :delete,
    class: 'btn btn-danger pull-right',
      data: { confirm: 'Tem certeza que quer apagar?' } if @meta.persisted? %>
    </div>
  </div>
  <% end %>

app/views/metas/detalhar.html.erb
<h1>Detalhar meta</h1>

<%= render 'formdetalhar', meta: @meta %>

app/views/metas/edit.html.erb
<h1>Editar Meta</h1>

<%= render 'form', meta: @meta %>

app/views/metas/index.html.erb
<div class="page-header">
  <h1>Metas de <%= mes = l @mes_referencia, :format => '%B' %> &nbsp;</h1>
  <div class="actions pull-right">
    <h2 class="lvh-label">
      <div class="btn-group">
        <%= link_to "<i class='fa fa-angle-left'></i>".html_safe,  {:periodo => @mes_referencia - 1.month}, :class => 'btn btn-default' %>
        <%= link_to mes, '', :class => 'btn btn-default' %>
        <%= link_to "<i class='fa fa-angle-right'></i>".html_safe, {:periodo => @mes_referencia + 1.month}, :class => 'btn btn-default' %>
      </div>
    </h2>
  </div>
  <%= link_to "Nova Meta", new_meta_path, class: 'btn btn-primary pull-left' %>
</div>

<div class="panel panel-default">
  <div class="panel panel-heading">
    <i class="fa fa-filter"></i>
    Responsável:
    <%= link_to "Todos", periodo: params[:periodo], com_responsavel: nil %>,
    <% Usuario.all.each do |u| %>
    <%= link_to u.nome,  periodo: params[:periodo], com_responsavel: u.id %> -
    <% end %>
    Status:
    <%= link_to "Não concluída", periodo: params[:periodo], com_responsavel: params[:com_responsavel],
     metas_not_done: params[:periodo] %> - 
    <%= link_to "Concluída", periodo: params[:periodo], com_responsavel: params[:com_responsavel],
     meta_done: params[:periodo] %>
  <span class="pull-right text-muted small"><em>Total <%= @metas.count %></em</span>
  </div>
  <% @bnf = Bonificacao.verifica_competencia(@mes_referencia) %>
  <table class="table table-condensed table-striped table-bordered table-hover">
    <% if @metas.present? %>
    <thead>
      <tr>
        <th>Nível</th>
        <th>Meta</th>
        <th>Detalhamento</th>
        <th>Status</th>
        <th>Responsável</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @metas.each do |meta| %>
      <% if meta.detalhamentos.present? %>      
      <% porcento = andamento(meta.id).to_i %>        
      <% end %>
      <tr>
        <td style="<%= background_meta(meta.nivel) %>" class="text-center"><strong><%= meta.nivel %></strong></td>
        <td class="<%= concluido(porcento) %>"><%= link_to meta.nome, meta %>
          <% if meta.detalhamentos.present? %>
          <% if andamento(meta.id).to_i == 100 %>
          <div class="progress">
            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= andamento(meta.id).to_i %>%;">
              <%= andamento(meta.id).to_i %>%
            </div>
          </div>
          <% else %>
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= andamento(meta.id).to_i %>%;">
              <%= andamento(meta.id).to_i %>%
            </div>
          </div>
          <% end %>
          <% end %>
        </td>
        <td class="col-sm-6  <%= concluido(porcento) %>">
          <% meta.detalhamentos.order('created_at').each do |item| %>
          <% if meta.detalhamentos.present? %>
          <p><%= item.item %></p>
          <% else %>
          <%= link_to 'Detalhar', detalhar_meta_path(meta), class: 'btn btn-primary btn-xs' %>
          <% end %>
          <% end %>
        </td>
        <td class="<%= concluido(porcento) %>" width='100'>
        <% if @bnf.present? %>
          <% if meta.status %>
            <spam class="texte-success fa fa-check-circle fa-2x"> </spam>
          <% else %>
            <spam class="text-danger fa fa-times-circle fa-2x"></spam>
          <% end %>
        <% else %>
            <% meta.detalhamentos.order('created_at').each do |item| %>
              <% if item.status %>
                  <input onchange="toggle_status(<%= item.id %>);" checked type="checkbox" data-toggle="toggle" data-on="Feito" data-off="Pendente" data-onstyle="success" data-size="mini" data-offstyle="default">              
                <% else %>                
                  <input onchange="toggle_status(<%= item.id %>);" type="checkbox" data-toggle="toggle" data-on="Feito" data-off="Pendente" data-onstyle="success" data-size="mini" data-offstyle="default">                
              <% end %>
            <% end %>
        <% end %>
        </td>
      </td>
      <td class="<%= concluido(porcento) %>">
        <%= meta.usuario.nome %>
      </td>
    </tr>
    <% end %>
  </tbody>
  <% else %>
  <tr>
    <td>
      <div class="alert alert-info">
        Nenhuma meta cadastrada nesse período. <%= link_to "Cadastrar nova", new_meta_path, class: "alert-link" %>.
      </div>
    </td>
  </tr>
  <% end %>
</table>

  <div class="panel panel-footer">
  <% if @bnf.present? %>
    <a class="btn btn-success disabled">Mês fechado</a>
    <%= link_to "Ver resultado", bonificacao_path(@bnf.first.id), class: "btn btn-primary" %>
  <% else %>
    <%= link_to "Fechar mês", fechar_mes_metas_path(data_referencia: @mes_referencia), class: "btn btn-success", data: { confirm: 'Tem certeza que deseja fechar o mês?' } %>
  <% end %>
  </div>
</div>

<script>

function toggle_status(id) {
  $.ajax({
    url:'/detalhamentos/'+id+'/toogle_status',
    type: 'GET'
  }).done(function() {
    console.log('alterado')
  });
}

</script>

app/views/metas/new.html.erb
<h1>Novo Meta</h1>

<%= render 'form', meta: @meta %>

app/views/metas/show.html.erb
<div class="page-header">
  <h1>
    <%= @meta.nome %>
  </h1>

  <div class="pull-right" >
    <%= link_to "Nova Meta", new_meta_path, class: 'btn btn-success' %>

    <%= link_to "Editar", edit_meta_path(@meta), class: 'btn btn-primary' %>

  </div>
</div>

<div class="col-lg-12">
  <div class="panel panel-default">
    <table class="table">
      <thead>
        <th>Ganho</th>
        <th>Tipo</th>
        <th>Dificuldade</th>
        <th>Coefi. Ganho</th>
        <th>Coefi. Tipo</th>
        <th>Coefi. Dificuldade</th>
        <th>Pontuação</th>
        <th>Nível meta</th>
        <th>Data cadastro</th>
      </thead>
      <tr>
        <td><%= @meta.ganho.nome %></td>
        <td><%= @meta.tipo.nome %></td>
        <td><%= @meta.dificuldade.nome %></td>
        <td><%= @meta.coeficienteganho %></td>
        <td><%= @meta.coeficientetipo %></td>
        <td><%= @meta.coeficientedificuldade %></td>
        <td><%= @meta.pontuacao %></td>
        <td><%= @meta.nivel %></td>
        <td><%= l @meta.created_at, format: :long %></td>
      </tr>
    </table>
  </div>
</div>

<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      Detalhamento da meta <%= link_to 'Adicionar item', detalhar_meta_path(@meta), class: 'btn btn-primary btn-xs' %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <% if @meta.detalhamentos.present? %>
      <table class="table">
        <thead>
          <th>Item</th>
          <th>Status</th>
        </thead>
        <tbody>
          <% @meta.detalhamentos.order('created_at').each do |item| %>
          <tr>
            <td class="col-sm-7">
              <p><%= item.item %></p>
            </td>
            <td class="col-sm-2">
              <% if item.status %>
              <p>
                <input onchange="toggle_status(<%= item.id %>);" checked type="checkbox" data-toggle="toggle" data-on="Concluída" data-off="Pendente" data-onstyle="success" data-size="mini" data-offstyle="default">
              </p>
              <% else %>
              <p>
                <input onchange="toggle_status(<%= item.id %>);" type="checkbox" data-toggle="toggle" data-on="Concluída" data-off="Pendente" data-onstyle="success" data-size="mini" data-offstyle="default">
              </p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
        <p class="text-info">Ainda não há detalhamento para essa meta</p>
        <%= link_to 'Detalhar', detalhar_meta_path(@meta), class: 'btn btn-primary btn-xs' %>
      <% end %>

    </div>
    <!-- /.panel-body -->
  </div>
  <!-- /.panel -->
</div>