config/routes.rb
Rails.application.routes.draw do
  resources :slames
  resources :sistemaslas
  resources :gruposlas
  resources :bonificacoes
  resources :detalhamentos do
    get 'toogle_status',  on: :member
  end
  resources :metas do
    get 'detalhar',       on: :member
    get 'fechar_mes',     on: :collection
  end
  resources :configs
  resources :ganhos
  resources :dificuldades
  resources :tipos
  devise_for :usuarios, path_prefix: :auth
  resources :usuarios
  root to: 'welcome#index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/config.rb
class Config < ApplicationRecord
end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  before_action :set_config, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @configs = Config.all
    respond_with(@configs)
  end

  def show
    respond_with(@config)
  end

  def new
    @config = Config.new
    respond_with(@config)
  end

  def edit
  end

  def create
    @config = Config.new(config_params)
    @config.save
    respond_with(@config, location: configs_path)
  end

  def update
    @config.update(config_params)
    respond_with(@config)
  end

  def destroy
    @config.destroy
    respond_with(@config)
  end

  private
    def set_config
      @config = Config.find(params[:id])
    end

    def config_params
      params.require(:config).permit(:valor_ganho, :valor_dificuldade, :valor_tipo)
    end
end

app/helpers/configs_helper.rb
module ConfigsHelper
end

app/views/configs/_form.html.erb
<%= simple_form_for(config, multipart: true) do |f| %>
<div class="panel panel-default">
  <div class="panel-body">
    <% if config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(config.errors.count, "erro") %></h2>

      <ul>
        <% config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="row">
      <%= f.input :valor_ganho, wrapper_html: {class: 'col-md-3'} %>
      <%= f.input :valor_dificuldade, wrapper_html: {class: 'col-md-3'} %>
      <%= f.input :valor_tipo, wrapper_html: {class: 'col-md-3'} %>
    </div>
  </div>

  <div class="panel-footer">
    <%= f.submit "Salvar", class: 'btn btn-primary' %> ou
    <%= link_to "Cancelar", :back, class: 'btn btn-default' %>
    <%= link_to "Apagar", @config,
    method: :delete,
    class: 'btn btn-danger pull-right',
    data: { confirm: 'Tem certeza que quer apagar?' } if @config.persisted? %>
  </div>
</div>
<% end %>

app/views/configs/edit.html.erb
<h1>Editar Configurações</h1>

<%= render 'form', config: @config %>

app/views/configs/index.html.erb
<div class="page-header">
  <h1>Configs</h1>
  <%= link_to "Novo Config", new_config_path, class: 'btn btn-primary' %>
</div>

<div class="panel panel-default">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Valor Ganho</th>
        <th>Valor Tipo</th>
        <th>Valor Dificuldade</th>
        <th>Data de cadastro</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @configs.each do |config| %>
        <tr>
          <td><%= link_to config.valor_ganho, config %></td>
          <td><%= link_to config.valor_tipo, config %></td>
          <td><%= link_to config.valor_dificuldade, config %></td>
          <td><%= l config.created_at, format: :long %></td>
          <td><%= link_to 'Editar', edit_config_path(config), class: 'btn btn-default btn-xs' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/configs/new.html.erb
<h1>Novo Configurações</h1>

<%= render 'form', config: @config %>

app/views/configs/show.html.erb
<div class="page-header">
  <h1>
    <%= @config.descricao %>
  </h1>
  <div class="pull-right">
    <%= link_to "Editar", edit_config_path(@config), class: 'btn btn-primary' %>
  </div>
</div>

<div class="panel panel-default">
  <table class="table">
    <tr>
      <td class="col-md-2">Descrição</td> <td><%= @config.descricao %></td>
    </tr>
    <tr>
      <td>Data do cadastro</td> <td><%= l @config.created_at %></td>
    </tr>
  </table>
</div>