config/routes.rb
Rails.application.routes.draw do
  resources :slames
  resources :sistemaslas
  resources :gruposlas
  resources :bonificacoes
  resources :detalhamentos do
    get 'toogle_status',  on: :member
  end
  resources :metas do
    get 'detalhar',       on: :member
    get 'fechar_mes',     on: :collection
  end
  resources :configs
  resources :ganhos
  resources :dificuldades
  resources :tipos
  devise_for :usuarios, path_prefix: :auth
  resources :usuarios
  root to: 'welcome#index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/detalhamento.rb
class Detalhamento < ApplicationRecord

  belongs_to :meta, optional: true

end

app/controllers/detalhamentos_controller.rb
class DetalhamentosController < ApplicationController
  before_action :set_detalhamento, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @detalhamentos = Detalhamento.all
    respond_with(@detalhamentos)
  end

  def show
    respond_with(@detalhamento)
  end

  def new
    @detalhamento = Detalhamento.new
    respond_with(@detalhamento)
  end

  def edit
  end

  def create
    @detalhamento = Detalhamento.new(detalhamento_params)
    @detalhamento.save
    respond_with(@detalhamento)
  end

  def toogle_status
    @detalhamento = Detalhamento.find(params[:id])
    @detalhamento.update_columns(status: !@detalhamento.status)
    render(nothing: true)
  end

  def update
    @detalhamento.update(detalhamento_params)
    respond_with(@detalhamento)
  end

  def destroy
    @detalhamento.destroy
    respond_with(@detalhamento)
  end

  private
    def set_detalhamento
      @detalhamento = Detalhamento.find(params[:id])
    end

    def detalhamento_params
      params.require(:detalhamento).permit(:item, :meta_id, :status)
    end
end

app/helpers/detalhamentos_helper.rb
module DetalhamentosHelper
end

app/views/detalhamentos/_form.html.erb
<%= simple_form_for(detalhamento, multipart: true) do |f| %>
<div class="panel panel-default">
  <div class="panel-body">
    <% if detalhamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detalhamento.errors.count, "erro") %></h2>

      <ul>
        <% detalhamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="row">
      <%= f.input :item %>
      <%= f.input :meta_id %>
      <%= f.input :status %>
    </div>
  </div>

  <div class="panel-footer">
    <%= f.submit "Salvar", class: 'btn btn-primary' %> ou
    <%= link_to "Cancelar", :back, class: 'btn btn-default' %>
    <%= link_to "Apagar", @detalhamento,
    method: :delete,
    class: 'btn btn-danger pull-right',
    data: { confirm: 'Tem certeza que quer apagar?' } if @detalhamento.persisted? %>
  </div>
</div>
<% end %>

app/views/detalhamentos/edit.html.erb
<h1>Editar Detalhamento</h1>

<%= render 'form', detalhamento: @detalhamento %>

app/views/detalhamentos/index.html.erb
<div class="page-header">
  <h1>Detalhamentos</h1>
  <%= link_to "Novo Detalhamento", new_detalhamento_path, class: 'btn btn-primary' %>
</div>

<div class="panel panel-default">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Descrição</th>
        <th>Data cadastro</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @detalhamentos.each do |detalhamento| %>
        <tr>
          <td><%= link_to detalhamento.descricao, detalhamento %></td>
          <td><%= l detalhamento.created_at, format: :xshort %></td>
          <td><%= link_to 'Editar', edit_detalhamento_path(detalhamento), class: 'btn btn-default btn-xs' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/detalhamentos/new.html.erb
<h1>Novo Detalhamento</h1>

<%= render 'form', detalhamento: @detalhamento %>

app/views/detalhamentos/show.html.erb
<div class="page-header">
  <h1>
    <%= @detalhamento.descricao %>
  </h1>
  <div class="pull-right">
    <%= link_to "Editar", edit_detalhamento_path(@detalhamento), class: 'btn btn-primary' %>
  </div>
</div>

<div class="panel panel-default">
  <table class="table">
    <tr>
      <td class="col-md-2">Descrição</td> <td><%= @detalhamento.descricao %></td>
    </tr>
    <tr>
      <td>Data do cadastro</td> <td><%= l @detalhamento.created_at %></td>
    </tr>
  </table>
</div>