config/routes.rb
Rails.application.routes.draw do
  resources :slames
  resources :sistemaslas
  resources :gruposlas
  resources :bonificacoes
  resources :detalhamentos do
    get 'toogle_status',  on: :member
  end
  resources :metas do
    get 'detalhar',       on: :member
    get 'fechar_mes',     on: :collection
  end
  resources :configs
  resources :ganhos
  resources :dificuldades
  resources :tipos
  devise_for :usuarios, path_prefix: :auth
  resources :usuarios
  root to: 'welcome#index'
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dificuldade.rb
class Dificuldade < ApplicationRecord

  validates :nome,
            :valor_dificuldade,
            presence: true

  has_many :meta, dependent: :destroy

end

app/controllers/dificuldades_controller.rb
class DificuldadesController < ApplicationController
  before_action :set_dificuldade, only: [:show, :edit, :update, :destroy]

  # GET /dificuldades
  # GET /dificuldades.json
  def index
    @dificuldades = Dificuldade.all
  end

  # GET /dificuldades/1
  # GET /dificuldades/1.json
  def show
  end

  # GET /dificuldades/new
  def new
    @dificuldade = Dificuldade.new
  end

  # GET /dificuldades/1/edit
  def edit
  end

  # POST /dificuldades
  # POST /dificuldades.json
  def create
    @dificuldade = Dificuldade.new(dificuldade_params)

    respond_to do |format|
      if @dificuldade.save
        format.html { redirect_to @dificuldade, notice: 'Dificuldade was successfully created.' }
        format.json { render :show, status: :created, location: @dificuldade }
      else
        format.html { render :new }
        format.json { render json: @dificuldade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dificuldades/1
  # PATCH/PUT /dificuldades/1.json
  def update
    respond_to do |format|
      if @dificuldade.update(dificuldade_params)
        format.html { redirect_to @dificuldade, notice: 'Dificuldade was successfully updated.' }
        format.json { render :show, status: :ok, location: @dificuldade }
      else
        format.html { render :edit }
        format.json { render json: @dificuldade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dificuldades/1
  # DELETE /dificuldades/1.json
  def destroy
    @dificuldade.destroy
    respond_to do |format|
      format.html { redirect_to dificuldades_url, notice: 'Dificuldade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dificuldade
      @dificuldade = Dificuldade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dificuldade_params
      params.require(:dificuldade).permit(:nome, :valor_dificuldade, :status)
    end
end

app/helpers/dificuldades_helper.rb
module DificuldadesHelper
end

app/views/dificuldades/_form.html.erb
<%= simple_form_for(dificuldade, multipart: true) do |f| %>
<div class="panel panel-default">
  <div class="panel-body">
    <% if dificuldade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dificuldade.errors.count, "erro") %></h2>

      <ul>
        <% dificuldade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="row">
      <%= f.input :nome, wrapper_html: {class: 'col-md-6'} %>
      <%= f.input :valor_dificuldade, wrapper_html: {class: 'col-md-2'} %>
      <%= f.input :status, wrapper_html: {class: 'col-md-2'} %>
    </div>
  </div>

  <div class="panel-footer">
    <%= f.submit "Salvar", class: 'btn btn-primary' %> ou
    <%= link_to "Cancelar", :back, class: 'btn btn-default' %>
    <%= link_to "Apagar", @dificuldade,
    method: :delete,
    class: 'btn btn-danger pull-right',
    data: { confirm: 'Tem certeza que quer apagar?' } if @dificuldade.persisted? %>
  </div>
</div>
<% end %>

app/views/dificuldades/edit.html.erb
<h1>Editar Dificuldade</h1>

<%= render 'form', dificuldade: @dificuldade %>

app/views/dificuldades/index.html.erb
<div class="page-header">
  <h1>Definição de dificuldades</h1>
  <%= link_to "Novo Dificuldade", new_dificuldade_path, class: 'btn btn-primary' %>
</div>

<div class="panel panel-default">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Dificuldades</th>
        <th>Valor</th>
        <th>Data cadastro</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @dificuldades.each do |dificuldade| %>
      <tr>
        <td><%= link_to dificuldade.nome, dificuldade %></td>
        <td><%= dificuldade.valor_dificuldade %></td>
        <td><%= l dificuldade.created_at, format: :long %></td>
        <td><%= link_to 'Editar', edit_dificuldade_path(dificuldade), class: 'btn btn-default btn-xs' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dificuldades/new.html.erb
<h1>Novo Dificuldade</h1>

<%= render 'form', dificuldade: @dificuldade %>

app/views/dificuldades/show.html.erb
<div class="page-header">
  <h1>
    <%= @dificuldade.nome %>
  </h1>
  <div class="pull-right">
    <%= link_to "Editar", edit_dificuldade_path(@dificuldade), class: 'btn btn-primary' %>
  </div>
</div>

<div class="panel panel-default">
  <table class="table">
    <tr>
      <td class="col-md-2">Descrição</td> <td><%= @dificuldade.nome %></td>
    </tr>
    <tr>
      <td class="col-md-2">Valor</td> <td><%= @dificuldade.valor_dificuldade %></td>
    </tr>
    <tr>
      <td>Data do cadastro</td> <td><%= l @dificuldade.created_at, format: :long %></td>
    </tr>
  </table>
</div>